name: Built and test by pull request

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    if: github.event.issue.pull_request != null && github.event.comment.body == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Specific Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "Build and test"
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.issue.pull_request.head.ref }}
