name: renovate

on:
  schedule:
    # 日本時間8時に実行
    - cron: '0 23 * * *'

jobs:
  renovate:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.0
        with:
          useSlim: false
          configurationFile: .github/workflows/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
